AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    ApiGatewayApiKey:
        Type: "AWS::ApiGateway::ApiKey"
        Properties:
            Enabled: true
            Name: "User"
