AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    CodeCommitRepository:
        Type: "AWS::CodeCommit::Repository"
        Properties:
            RepositoryName: "indexphotos"

    CodeCommitRepository2:
        Type: "AWS::CodeCommit::Repository"
        Properties:
            RepositoryName: "searchphotos"

